
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

# Specify the build environment
build:
  image: latest
  # Uncomment the line below if you need a specific OS
  # os: ubuntu-20.04

python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub
