
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

# Specify the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

# Define the Python version and requirements
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

# Specify the formats for the documentation build
formats:
  - htmlzip
  - pdf
  - epub

